# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/hcpworks/"
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    assignees:
      - "in0ho1no"
    labels:
      - "dependencies"
    commit-message:
      prefix: "npm Security update"
      include: "scope"
    target-branch: "develop"
    security-updates-only: true

  - package-ecosystem: "npm"
    directory: "/hcpworks/"
    schedule:
      interval: "monthly"
      time: "17:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    assignees:
      - "in0ho1no"
    labels:
      - "dependencies"
    commit-message:
      prefix: "npm"
      include: "scope"
    target-branch: "dependency-eliminate"
