name: Test Report

on:
  workflow_run:
    workflows: ["VSCode Extension Test"]
    types:
      - completed

permissions:
  checks: write
  actions: read  # artifact のダウンロードに必要

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Test Report
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        with:
          artifact: test-results
          name: Mocha Tests
          path: '*.xml'
          reporter: java-junit
          fail-on-error: true
          fail-on-empty: false
